show_downloads: false
page-header: false
google_analytics: # Add your ID here if you have one
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # Provides the "Albino/Dark" aesthetic

