title: Santhosh C
logo: /assets/profile-pic.png # Optional: add a square photo here
description: Data Analyst | AI-Driven Analytics | SQL Intelligence
show_downloads: false
google_analytics: # Add your ID if you want to track visitors
theme: jekyll-theme-minimal

# Navigation Links
nav:
  - text: LinkedIn
    url: https://linkedin.com/in/santhoshc
  - text: Portfolio
    url: /
  - text: Contact
    url: mailto:santhosh08092001@gmail.com
